version: "3.8"

services:
  app:
    build: .
    container_name: app
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    depends_on:
      - test

  test:
    build: .
    container_name: test
    volumes:
      - ./test:/app/test
    command: pytest /test
