name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

jobs:
  # Job to run tests and static analysis on push
  run-tests:
    name: Run Tests and Static Analysis
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          pip install flake8 

      - name: Run Flake8 in src
        run: flake8 src

      - name: Run Flake8 in test
        run: flake8 test

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Run tests in Docker container
        run: docker-compose exec -T app pytest --maxfail=1 --disable-warnings

      - name: Shut down Docker Compose
        run: docker-compose down

  # Job to build and publish Docker image on pull request
  publish-docker:
    name: Build and Publish Docker Images
    runs-on: ubuntu-latest
    needs: run-tests

    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository }}/app:pr-${{ github.event.number }} .

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true



